# -*- coding: utf-8 -*-
"""Produtos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15maMUG0TkEqVMdmBF1PEkMIkd1CfFEw5
"""

produtos = {}

# funções
def NaoNulo(produto, final): #
      while produto == "" or produto[0] == " " or produto[final] == " ":
        print("Nomes em branco e iniciados ou terminados em branco não são válidos\n")
        produto = input(f"Insira o nome do produto {i+1}: ")
        final = len(produto)- 1


      return produto

def SomaTotal(produtos):
    soma=0
    for i in produtos:
        soma+=produtos[i]

    return soma

def produto_mais_caro(produtos):

    ListaCaro=[]
    maior = next(iter(produtos))
    for i in list(produtos.keys())[1:]:     #Identifica o maior
        if produtos[maior]<produtos[i]:
            maior=i


    for i in list(produtos.keys()):
        if produtos[maior]  == produtos[i] and maior!=i: #Une os iguais
            print
            ListaCaro.append(i)
            ListaCaro.append(produtos[i])


    if len(ListaCaro)>0:     #Verifica quantos iguais
        ListaCaro.append(maior)
        ListaCaro.append(produtos[maior])

    else: #Finaliza a função depois de exibir o único produto
        return print("Filtro do produto mais caro:","\n" "Nome:",maior,"\n" "Valor:", produtos[maior])
        return

    comprimentoLista=len(ListaCaro)  #Mostra todos os produtos maiores
    print("Filtro dos produtos mais caros:","\n")

    for i in range(0,comprimentoLista,2):
         print("Nome:",ListaCaro[i],"\n" "Valor:", ListaCaro[i+1<comprimentoLista])

def produto_mais_barato(produtos):
    listaBaratos=[]
    menor = next(iter(produtos))
    for i in list(produtos.keys())[1:]:     #Identifica o menor
        if produtos[menor]>produtos[i]:
            menor=i


    for i in list(produtos.keys()):
        if produtos[menor]  == produtos[i] and menor!=i: #Une os iguai
            print
            listaBaratos.append(i)
            listaBaratos.append(produtos[i])


    if len(listaBaratos)>0:     #Verifica quantos iguais
        listaBaratos.append(menor)
        listaBaratos.append(produtos[menor])

    else: #Finaliza a função depois de exibir o único produto
        return print("Filtro do produto mais barato:","\n" "Nome:",menor,"\n" "Valor:", produtos[menor])
        return

    comprimentoLista=len(listaBaratos)  #Mostra todos os produtos menores
    print("Filtro do produtos mais baratos:","\n")

    for i in range(0,comprimentoLista,2):
         print("Nome:",listaBaratos[i],"\n" "Valor:", listaBaratos[i+1<comprimentoLista])

def NomeNaoRepetido(produto,produtos, final):

    while produto in produtos or produto[0] == " " or produto[final] == " " :   #Também evita que cadastre nomes iguais
                                                                                #usando espaço antes ou depois do nome
             print("Nao pode haver produtos com nomes iguais")
             produto = input(f"Insira o nome do produto {i+1}: ")
             final=len(produto)-1
    produtos[produto] = 0

    return   produto
def numero_nome(produto,indice):
    
    while True:
        
        for i in produto:
            try:
                
                type(float(i))
                        
            except ValueError:
                    return produto
        print("É necessário haver letras no nome")
        produto = input(f"Insira o nome do produto {indice+1}: ")
            
#Input dos nomes das keys do dicionário

print("-"*15, "NOMES DOS PRODUTOS","-"*15,"\n")
while True:
    try:
        # Tenta converter a entrada para um número inteiro
        items = int(input("Insira a quantidade de items a serem cadastrados: "))
        
        # Garante que a quantidade não seja negativa
        if items < 0:
            print("Por favor, digite um número maior ou igual a zero.")
            continue
            
        break  
        
    except ValueError:
        
        print("Erro: Entrada inválida! Digite apenas números inteiros (ex: 5, 10, 22).")

for i in range(items):
    produto = input(f"Insira o nome do produto {i+1}: ")
    final=len(produto)-1
    for j in produto:
        if j.isdigit():
            produto=numero_nome(produto,i )
            
        else:
        
            if produto == "" or produto[0] == " " or produto[final]== " ":
                produto=NaoNulo(produto, final)
        
            if produto in produtos:
                  NomeNaoRepetido(produto,produtos, final)
        
        if produto == "" or produto[0] == " " or produto[final]== " ":
                produto=NaoNulo(produto, final)
        
        if produto in produtos:
                  NomeNaoRepetido(produto,produtos, final)
    produtos[produto] = 0



print("\n")

#Input dos valores numéricos das keys do dicionário
print("-"*15, "VALORES DOS PRODUTOS","-"*15,"\n")

for i in produtos:
    while True:
        try:
           preco = float(input(f"Insira o preço de {i}: "))
           if preco <= 0:
                print("O preço não pode ser nulo ou negativo.")
           else:
                break
        except ValueError:
            print("Valor inválido. Digite um número.")

    produtos[i] = preco

print( "\n")

#Exibe as keys e seus respectivos valores do dicionário
print("-"*15, "PRODUTOS","-"*15,"\n")

for i in produtos:
    print("Produto", i)
    print("Valor:",produtos[i], "\n")

print( "\n")

#Exibe as estatisticas das valores do dicionário
print("-"*15, "ESTATÍSTICAS","-"*15,"\n")
print("\n")
print("Soma total dos produtos:", SomaTotal(produtos))
print("\n")
print("Média dos produtos:", SomaTotal(produtos)/5)
print("\n")
produto_mais_caro(produtos)
print("\n")
produto_mais_barato(produtos)
print("\n")
qtd = int(input('Digite a quantidade de produtos que deseja remover: '))
if qtd==0:
    pass
else:
    while not qtd==0:
        item = input('Digite o nome do produtos que deseja remover: ')
        if item in produtos :
            del produtos[item]
        else:
            qtd+=1
            print("Nome errado")
    
        qtd-=1
    for i in produtos:
        print("Nome: ",i,"Preço: ", produtos[i],"\n")
